### ISSUE TITLE
关于KL散度计算的问题

### ISSUE THREAD

**Issue by xnuohz** [duchao0726/DUAL#1]
大佬你好，看了你的code的实现，有一些疑问

- 为什么p分布的协方差矩阵初始值要用cholesky分解K(Z, Z)的方式初始化

**Comment by duchao0726** [comment]
你好，谢谢关注我们的工作

> * 为什么p分布的协方差矩阵初始值要用cholesky分解K(Z, Z)的方式初始化

只有q分布的协方差矩阵是参数化的，为了保证正定性，通过Cholesky三角阵初始化比较方便；p分布的协方差矩阵是由Kernel和Z确定的，代码中并没有“初始化”协方差矩阵，只是求了它的Cholesky分解Lp。通过先得到Lp，然后用triangular_solve相当于求了Lp的逆，然后平方，这样等价于用了K(Z,Z)的逆

**Comment by xnuohz** [comment]
明白了，谢谢
